partCount: 3
parts:
  default_0:
    loc: /home/jat/MyFiles/coding/Go/BasaltDB/BasaltDB/default/default_0.gob
  default_1:
    loc: /home/jat/MyFiles/coding/Go/BasaltDB/BasaltDB/default/default_1.gob
  default_2:
    loc: /home/jat/MyFiles/coding/Go/BasaltDB/BasaltDB/default/default_2.gob
